<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Lecture 2: The grammar of graphics and filtering data</title>

<script src="site_libs/header-attrs-2.29/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cerulean.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/font-awesome-6.5.2/css/all.min.css" rel="stylesheet" />
<link href="site_libs/font-awesome-6.5.2/css/v4-shims.min.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>



<style type="text/css">
  code {
    white-space: pre;
  }
  .sourceCode {
    overflow: visible;
  }
</style>
<style type="text/css" data-origin="pandoc">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  background-color: #f8f8f8; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #204a87; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #8f5902; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #204a87; font-weight: bold; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #ce5c00; font-weight: bold; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    var j = 0;
    while (j < rules.length) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") {
        j++;
        continue;
      }
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') {
        j++;
        continue;
      }
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>







<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html"><img id="logo" style="width: 200px;" src="figures/WMA_logo.png" /></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">
    <span class="fa fa-home"></span>
     
    Home
  </a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    <span class="fa fa-sign-in"></span>
     
    Get Started
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="lecture0.html">Lecture 0</a>
    </li>
    <li>
      <a href="ps0.html">Problem Set 0</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    <span class="fa fa-institution"></span>
     
    Academy
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="lecture1.html">Lecture 1</a>
    </li>
    <li>
      <a href="lecture2.html">Lecture 2</a>
    </li>
    <li>
      <a href="lecture3.html">Lecture 3</a>
    </li>
    <li>
      <a href="lecture4.html">Lecture 4</a>
    </li>
    <li class="divider"></li>
    <li>
      <a href="ps1.html">Problem Set 1</a>
    </li>
    <li>
      <a href="ps2.html">Problem Set 2</a>
    </li>
    <li>
      <a href="ps3.html">Problem Set 3</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    <span class="fa fa-dribbble"></span>
     
    Training Camp
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="tc_lecture1.html">Lecture 1</a>
    </li>
    <li>
      <a href="tc_lecture2.html">Lecture 2</a>
    </li>
    <li>
      <a href="tc_lecture3.html">Lecture 3</a>
    </li>
    <li>
      <a href="tc_lecture4.html">Lecture 4</a>
    </li>
    <li>
      <a href="tc_lecture5.html">Lecture 5</a>
    </li>
    <li class="divider"></li>
    <li>
      <a href="tc_ps1.html">Problem Set 1</a>
    </li>
    <li>
      <a href="tc_ps2.html">Problem Set 2</a>
    </li>
    <li>
      <a href="tc_ps3.html">Problem Set 3</a>
    </li>
    <li class="divider"></li>
    <li>
      <a href="tc_lecture_data_sources.html">Data Sources Lecture</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Lecture 2: The grammar of graphics and
filtering data</h1>

</div>


<p>We’re going to pick up right where we left off yesterday in <a
href="tc_ps1.html">Problem Set 1</a>, where you wrote a script to create
a <code>tbl</code> containing several shooting statistics for NBA
players between the 1996-97 season and the 2015-16 season. Your script
could look something like what is the code block below, and for reasons
that will become clear shortly, we are going to call our tbl
<code>raw_shooting</code> (remember: writing code in script files is
good practice!)</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" tabindex="-1"></a><span class="co"># Read in data</span></span>
<span id="cb1-3"><a href="#cb1-3" tabindex="-1"></a>raw_shooting <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="at">file =</span> <span class="st">&quot;data/nba_shooting.csv&quot;</span>)</span></code></pre></div>
<pre><code>## Rows: 7447 Columns: 8
## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: &quot;,&quot;
## chr (1): PLAYER
## dbl (7): SEASON, FGM, FGA, TPM, TPA, FTM, FTA
## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" tabindex="-1"></a><span class="co"># Create new columns</span></span>
<span id="cb3-2"><a href="#cb3-2" tabindex="-1"></a>raw_shooting <span class="ot">&lt;-</span></span>
<span id="cb3-3"><a href="#cb3-3" tabindex="-1"></a>  <span class="fu">mutate</span>(raw_shooting,</span>
<span id="cb3-4"><a href="#cb3-4" tabindex="-1"></a>         <span class="at">FGP =</span> FGM <span class="sc">/</span> FGA,</span>
<span id="cb3-5"><a href="#cb3-5" tabindex="-1"></a>         <span class="at">TPP =</span> TPM <span class="sc">/</span> TPA,</span>
<span id="cb3-6"><a href="#cb3-6" tabindex="-1"></a>         <span class="at">FTP =</span> FTM <span class="sc">/</span> FTA,</span>
<span id="cb3-7"><a href="#cb3-7" tabindex="-1"></a>         <span class="at">eFGP =</span> (FGM <span class="sc">+</span> <span class="fl">0.5</span> <span class="sc">*</span> TPM) <span class="sc">/</span> (FGA),</span>
<span id="cb3-8"><a href="#cb3-8" tabindex="-1"></a>         <span class="at">PTS =</span> FTM <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> FGM <span class="sc">+</span> TPM,</span>
<span id="cb3-9"><a href="#cb3-9" tabindex="-1"></a>         <span class="at">TSP =</span> PTS<span class="sc">/</span>(<span class="dv">2</span> <span class="sc">*</span> (FGA <span class="sc">+</span> <span class="fl">0.44</span> <span class="sc">*</span> FTA)))</span>
<span id="cb3-10"><a href="#cb3-10" tabindex="-1"></a><span class="co"># Sort by the TSP in descending order</span></span>
<span id="cb3-11"><a href="#cb3-11" tabindex="-1"></a>raw_shooting <span class="ot">&lt;-</span> <span class="fu">arrange</span>(raw_shooting, <span class="fu">desc</span>(TSP))</span></code></pre></div>
<p>As we learned at the end of <a href="tc_lecture1.html">Lecture 1</a>,
rather than repeatedly referring to our <code>tbl</code>, we can use the
pipe <code>%&gt;%</code> to chain together our operations for a much
<em>cleaner</em> chunk of code:</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" tabindex="-1"></a><span class="co"># First read in the data, assigning pipeline to raw_shooting</span></span>
<span id="cb4-2"><a href="#cb4-2" tabindex="-1"></a>raw_shooting <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="at">file =</span> <span class="st">&quot;data/nba_shooting.csv&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb4-3"><a href="#cb4-3" tabindex="-1"></a>  <span class="co"># Next create the new columns</span></span>
<span id="cb4-4"><a href="#cb4-4" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">FGP =</span> FGM <span class="sc">/</span> FGA,</span>
<span id="cb4-5"><a href="#cb4-5" tabindex="-1"></a>         <span class="at">TPP =</span> TPM <span class="sc">/</span> TPA,</span>
<span id="cb4-6"><a href="#cb4-6" tabindex="-1"></a>         <span class="at">FTP =</span> FTM <span class="sc">/</span> FTA,</span>
<span id="cb4-7"><a href="#cb4-7" tabindex="-1"></a>         <span class="at">eFGP =</span> (FGM <span class="sc">+</span> <span class="fl">0.5</span> <span class="sc">*</span> TPM) <span class="sc">/</span> (FGA),</span>
<span id="cb4-8"><a href="#cb4-8" tabindex="-1"></a>         <span class="at">PTS =</span> FTM <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> FGM <span class="sc">+</span> TPM,</span>
<span id="cb4-9"><a href="#cb4-9" tabindex="-1"></a>         <span class="at">TSP =</span> PTS <span class="sc">/</span> (<span class="dv">2</span> <span class="sc">*</span> (FGA <span class="sc">+</span> <span class="fl">0.44</span> <span class="sc">*</span> FTA))) <span class="sc">%&gt;%</span></span>
<span id="cb4-10"><a href="#cb4-10" tabindex="-1"></a>  <span class="co"># And finally sort by TSP</span></span>
<span id="cb4-11"><a href="#cb4-11" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(TSP)) </span></code></pre></div>
<div id="introduction-to-ggplot2" class="section level2">
<h2>Introduction to ggplot2</h2>
<p>We will use visualizations to answer some questions about the data.
Specifically, we will study the distribution of the individual columns
as well as try to understand the relationship between pairs of
variables. For instance, are players attempting and making more three
point shots now than they did 10 years ago?</p>
<p>Throughout the week, we will be using the popular <a
href="https://ggplot2.tidyverse.org"><code>ggplot2</code></a> package
(again created by Hadley Wickham and a member of the
<code>tidyverse</code>) for all of our data visualizations. The
<code>gg</code> stands for the <strong>grammar of graphics</strong>, an
intuitive framework for data visualization. Given a dataset, such as
<code>raw_shooting</code>, we want to map the columns to certain
<strong>aesthetics</strong> of a visualization, such as the x-axis,
y-axis, size, color, etc. Then a geometric object is used to represent
the aesthetics visually such as a barchart or scatterplot. This
framework separates the process of visualization into different
components: data, aesthetic mappings, and geometric objects. These
components are then added together (or <strong>layered</strong>) to
produce the final graph. The <code>ggplot2</code> package is the most
popular implementation of the <strong>grammar of graphics</strong> and
is relatively easy to use.</p>
<p>As you saw in Prof. Wyner’s lectures, histograms are a powerful way
to describe a single dataset. Let’s start with making a histogram of
field-goal percentage (FGP). To do so with <code>ggplot2</code>, we
start by telling <code>R</code> which <code>tbl</code> we want to use as
the data for the plot. This is done using the <code>ggplot()</code>
function:</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> raw_shooting)</span></code></pre></div>
<p><img src="tc_lecture2_files/figure-html/ggplot-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>As you can see, nothing is displayed! That’s because we’ve just
initialized the dataset to be used for creating the plot. Next, we need
to map variables/columns from the data to
<strong>aesthetics</strong>/properties of the plot. Examples
include:</p>
<ul>
<li><code>x</code>: the variable that will be on the x-axis</li>
<li><code>y</code>: the variable that will be on the y-axis</li>
<li><code>color</code>: the variable that categorizes data by color</li>
<li><code>shape</code>: the variable that categorizes data by shape</li>
</ul>
<p>For the histogram, we map FGP to the <code>x</code> aesthetic with
the <code>aes()</code> functions, displaying values of FGP along the
x-axis:</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> raw_shooting, <span class="fu">aes</span>(<span class="at">x =</span> FGP))</span></code></pre></div>
<p><img src="tc_lecture2_files/figure-html/ggplot%20fgp-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Now we can see an axis for FGP, but still no histogram! That’s
because we need to <strong>add</strong> the geometric layer of the
histogram to the plot. The various geometric objects available in
<code>ggplot2</code> are referred to as <code>geom</code>s, and these
ultimately determine the type of play that will be created. Examples
include:</p>
<ul>
<li><code>geom_point()</code>: creates a scatterplot</li>
<li><code>geom_histogram()</code>: creates a histogram</li>
<li><code>geom_line()</code>: creates a line</li>
<li><code>geom_boxplot()</code>: creates a boxplot</li>
</ul>
<p>To display the FGP histogram, we will simply add the
<code>geom_histogram()</code> layer to the plot using the <code>+</code>
operator:</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> raw_shooting, <span class="fu">aes</span>(<span class="at">x =</span> FGP)) <span class="sc">+</span></span>
<span id="cb7-2"><a href="#cb7-2" tabindex="-1"></a>  <span class="fu">geom_histogram</span>()</span></code></pre></div>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="tc_lecture2_files/figure-html/geom_hist-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>And of course, we can equivalently generate the same figure by
<strong>piping</strong> our dataset into the <code>ggplot</code>
function. The remaining examples will use the pipe operator
<code>%&gt;%</code> for the remainder of this week, emphasizing how you
can manipulate the <code>tbl</code> with various other functions prior
to displaying the data:</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" tabindex="-1"></a>raw_shooting <span class="sc">%&gt;%</span></span>
<span id="cb9-2"><a href="#cb9-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> FGP)) <span class="sc">+</span></span>
<span id="cb9-3"><a href="#cb9-3" tabindex="-1"></a>  <span class="fu">geom_histogram</span>()</span></code></pre></div>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="tc_lecture2_files/figure-html/ggplot%20pipe-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Each <code>geom</code> has it various attributes that can be modified
whether by mapping variables with <code>aes</code> or <em>global</em>
settings that affects the final displayed plot. A common problem faced
with histograms is determining the width of the bins or number of bins -
how much smoothing do we want of the data? You might have noticed that
by default <code>geom_histogram</code> is using 30 bins and prints out a
message for us about this decision. We can easily modify the number of
bins in the <code>geom_histogram</code> function using the
<code>bins</code> argument:</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" tabindex="-1"></a>raw_shooting <span class="sc">%&gt;%</span></span>
<span id="cb11-2"><a href="#cb11-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> FGP)) <span class="sc">+</span></span>
<span id="cb11-3"><a href="#cb11-3" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">50</span>)</span></code></pre></div>
<p><img src="tc_lecture2_files/figure-html/hist%20bins-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Or we directly specify the width of the bins reflecting the range of
FGP included in each bin using <code>binwidth</code>:</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" tabindex="-1"></a>raw_shooting <span class="sc">%&gt;%</span></span>
<span id="cb12-2"><a href="#cb12-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> FGP)) <span class="sc">+</span></span>
<span id="cb12-3"><a href="#cb12-3" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="fl">0.05</span>)</span></code></pre></div>
<p><img src="tc_lecture2_files/figure-html/unnamed-chunk-1-1.png" width="672" style="display: block; margin: auto;" /></p>
<p><strong>Now you should spend time making histograms of FTP and TPP,
and other variables created in code above. Discuss the differences with
others.</strong></p>
</div>
<div id="filtering" class="section level2">
<h2>Filtering</h2>
<p>By this point, it should be clear that there are a number of rather
curious features in our dataset. For instance, there seem to be several
players who have never made a field goal but have made every one of
their free throw attempts. As it turns out, we have several players who
have attempted fewer than 5 field goals in a single season. We’d like to
remove all of the players who have not attempted a considerable number
of field goal attempts and three point attempts in order to understand
how the rate and efficiency of three point shots has changed over
time.</p>
<p>The <code>filter()</code> function is used to pull out subsets of
observations that satisfy some logical condition like
<code>FGA &gt; 100</code> or <code>FGA &gt; 100</code> and
<code>FTA &gt; 50</code>. To make such comparisons in R, we have the
following operators available at our disposal:</p>
<ul>
<li><code>==</code> for “equal to”</li>
<li><code>!=</code> for “not equal to”</li>
<li><code>&lt;</code> and <code>&lt;=</code> for “less than” and “less
than or equal to”</li>
<li><code>&gt;</code> and <code>&gt;=</code> for “greater than” and
“greater than or equal to”</li>
<li><code>&amp;</code>, <code>|</code>, <code>!</code> for “AND” and
“OR” and “NOT”</li>
</ul>
<p>The code below filter out all of the players with at least 100 field
goals in a single season.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" tabindex="-1"></a>raw_shooting <span class="sc">%&gt;%</span></span>
<span id="cb13-2"><a href="#cb13-2" tabindex="-1"></a>  <span class="fu">filter</span>(FGA <span class="sc">&gt;</span> <span class="dv">100</span>)</span></code></pre></div>
<pre><code>## # A tibble: 6,295 × 14
##    PLAYER   SEASON   FGM   FGA   TPM   TPA   FTM   FTA     FGP     TPP     FTP    eFGP   PTS     TSP
##    &lt;chr&gt;     &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;
##  1 Chris W…   2013   110   153     0     1    39    58 0.71895 0       0.67241 0.71895   259 0.72541
##  2 Tyson C…   2012   241   355     0     2   217   315 0.67887 0       0.68889 0.67887   699 0.70806
##  3 Kyle Ko…   2015   292   600   221   449   106   118 0.48667 0.49220 0.89831 0.67083   911 0.69871
##  4 Steve N…   2012   161   337   133   282    22    26 0.47774 0.47163 0.84615 0.67507   477 0.68448
##  5 Chris A…   2014   177   275     3    12   120   169 0.64364 0.25    0.71006 0.64909   477 0.68268
##  6 Jeremy …   2011    76   115     0     1    26    37 0.66087 0       0.70270 0.66087   178 0.67794
##  7 Carlos …   2001    75   110     0     1    29    52 0.68182 0       0.55769 0.68182   179 0.67354
##  8 Mason P…   2014   199   302     0     3   122   195 0.65894 0       0.62564 0.65894   520 0.67045
##  9 Stephen…   2016   805  1597   402   887   363   400 0.50407 0.45321 0.9075  0.62993  2375 0.66977
## 10 Brent B…   2004   215   427   114   252    91   110 0.50351 0.45238 0.82727 0.63700   635 0.66786
## # ℹ 6,285 more rows</code></pre>
<p>When we run this code, you’ll notice that R prints out a
<code>tbl</code> with 6,295 rows.</p>
<p>We can also filter on more complicated conditions constructed using
the AND, OR, and NOT operators: <code>&amp;</code>, <code>|</code>, and
<code>!</code>. For instance, to filter observations with at least 100
field goal attempts OR 50 three point attempts, we would do</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" tabindex="-1"></a>raw_shooting <span class="sc">%&gt;%</span></span>
<span id="cb15-2"><a href="#cb15-2" tabindex="-1"></a>  <span class="fu">filter</span>(FGA <span class="sc">&gt;=</span> <span class="dv">100</span> <span class="sc">|</span> TPA <span class="sc">&gt;=</span> <span class="dv">50</span>)</span></code></pre></div>
<pre><code>## # A tibble: 6,328 × 14
##    PLAYER   SEASON   FGM   FGA   TPM   TPA   FTM   FTA     FGP     TPP     FTP    eFGP   PTS     TSP
##    &lt;chr&gt;     &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;
##  1 Chris W…   2013   110   153     0     1    39    58 0.71895 0       0.67241 0.71895   259 0.72541
##  2 Tyson C…   2012   241   355     0     2   217   315 0.67887 0       0.68889 0.67887   699 0.70806
##  3 Kyle Ko…   2015   292   600   221   449   106   118 0.48667 0.49220 0.89831 0.67083   911 0.69871
##  4 Steve N…   2012   161   337   133   282    22    26 0.47774 0.47163 0.84615 0.67507   477 0.68448
##  5 Chris A…   2014   177   275     3    12   120   169 0.64364 0.25    0.71006 0.64909   477 0.68268
##  6 Jeremy …   2011    76   115     0     1    26    37 0.66087 0       0.70270 0.66087   178 0.67794
##  7 Carlos …   2001    75   110     0     1    29    52 0.68182 0       0.55769 0.68182   179 0.67354
##  8 Brian C…   2011    43   100    42    87    17    18 0.43    0.48276 0.94444 0.64      145 0.67179
##  9 Mason P…   2014   199   302     0     3   122   195 0.65894 0       0.62564 0.65894   520 0.67045
## 10 Stephen…   2016   805  1597   402   887   363   400 0.50407 0.45321 0.9075  0.62993  2375 0.66977
## # ℹ 6,318 more rows</code></pre>
<p>We may combine these constraints by enclosing them in
parentheses.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" tabindex="-1"></a>raw_shooting <span class="sc">%&gt;%</span></span>
<span id="cb17-2"><a href="#cb17-2" tabindex="-1"></a>  <span class="fu">filter</span>((FGA <span class="sc">&gt;=</span> <span class="dv">100</span> <span class="sc">&amp;</span> TPA <span class="sc">&gt;=</span> <span class="dv">50</span>) <span class="sc">|</span> (FGP <span class="sc">&gt;=</span> <span class="fl">0.45</span> <span class="sc">&amp;</span> FGP <span class="sc">&lt;=</span> <span class="fl">0.5</span>))</span></code></pre></div>
<pre><code>## # A tibble: 4,837 × 14
##    PLAYER   SEASON   FGM   FGA   TPM   TPA   FTM   FTA     FGP     TPP     FTP    eFGP   PTS     TSP
##    &lt;chr&gt;     &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;
##  1 Keith B…   2014     3     6     3     6     3     3 0.5     0.5     1       0.75       12 0.81967
##  2 Kyle Ko…   2015   292   600   221   449   106   118 0.48667 0.49220 0.89831 0.67083   911 0.69871
##  3 Aleksan…   1997     8    16     5     7     4     5 0.5     0.71429 0.8     0.65625    25 0.68681
##  4 Steve N…   2012   161   337   133   282    22    26 0.47774 0.47163 0.84615 0.67507   477 0.68448
##  5 Brian C…   2011    43   100    42    87    17    18 0.43    0.48276 0.94444 0.64      145 0.67179
##  6 Stephen…   2016   805  1597   402   887   363   400 0.50407 0.45321 0.9075  0.62993  2375 0.66977
##  7 Brent B…   2004   215   427   114   252    91   110 0.50351 0.45238 0.82727 0.63700   635 0.66786
##  8 Manu Gi…   2012   150   285    52   126    88   101 0.52632 0.41270 0.87129 0.61754   440 0.66780
##  9 Steve K…   1997   249   467   110   237    54    67 0.53319 0.46414 0.80597 0.65096   662 0.66669
## 10 Brent B…   2007   202   425   128   287   103   117 0.47529 0.44599 0.88034 0.62588   635 0.66634
## # ℹ 4,827 more rows</code></pre>
<p>What if we wanted to pull out the observations corresponding to the
2015-16 and 2014-15 season? We could do something like
<code>filter(raw_shooting, (SEASON == 2016) | (SEASON == 2015))</code>,
which would be perfectly fine. However, what if we wanted data from
1998-99, 2011-12, and 2015-16? Typing a lot of expressions like
<code>SEASON == ...</code> would be rather tedious. The
<code>%in%</code> operator lets us avoid this tedium:</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" tabindex="-1"></a>raw_shooting <span class="sc">%&gt;%</span></span>
<span id="cb19-2"><a href="#cb19-2" tabindex="-1"></a>  <span class="fu">filter</span>(SEASON <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">1999</span>, <span class="dv">2012</span>, <span class="dv">2016</span>))</span></code></pre></div>
<pre><code>## # A tibble: 1,150 × 14
##    PLAYER   SEASON   FGM   FGA   TPM   TPA   FTM   FTA     FGP     TPP     FTP    eFGP   PTS     TSP
##    &lt;chr&gt;     &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;
##  1 Tyson W…   1999     1     1     1     1     1     2 1       1       0.5     1.5         4 1.0638 
##  2 Tyson C…   2012   241   355     0     2   217   315 0.67887 0       0.68889 0.67887   699 0.70806
##  3 Jorge G…   2016     6    11     0     2    10    11 0.54545 0       0.90909 0.54545    22 0.69444
##  4 Steve N…   2012   161   337   133   282    22    26 0.47774 0.47163 0.84615 0.67507   477 0.68448
##  5 Sam Jac…   1999     3     5     0     1     2     2 0.6     0       1       0.6         8 0.68027
##  6 Stephen…   2016   805  1597   402   887   363   400 0.50407 0.45321 0.9075  0.62993  2375 0.66977
##  7 Manu Gi…   2012   150   285    52   126    88   101 0.52632 0.41270 0.87129 0.61754   440 0.66780
##  8 James H…   2012   309   629   114   292   312   369 0.49126 0.39041 0.84553 0.58188  1044 0.65962
##  9 Steve N…   2016     8    18     7    15     1     1 0.44444 0.46667 1       0.63889    24 0.65076
## 10 Brad Mi…   1999    78   138     1     2    81   102 0.56522 0.5     0.79412 0.56884   238 0.65070
## # ℹ 1,140 more rows</code></pre>
<p>We could also filter out data from the two lockout-shortened seasons,
1998-99 and 2011-12 using a combination of the NOT <code>!</code>
operator and <code>%in%</code>.</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" tabindex="-1"></a>raw_shooting <span class="sc">%&gt;%</span></span>
<span id="cb21-2"><a href="#cb21-2" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span>SEASON <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">1999</span>, <span class="dv">2012</span>))</span></code></pre></div>
<pre><code>## # A tibble: 6,721 × 14
##    PLAYER   SEASON   FGM   FGA   TPM   TPA   FTM   FTA     FGP     TPP     FTP    eFGP   PTS     TSP
##    &lt;chr&gt;     &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;
##  1 Dajuan …   2007     1     1     1     1     1     2 1       1       0.5     1.5         4 1.0638 
##  2 Amir Jo…   2006     7    10     2     3     4     4 0.7     0.66667 1       0.8        20 0.85034
##  3 Keith B…   2014     3     6     3     6     3     3 0.5     0.5     1       0.75       12 0.81967
##  4 Steve N…   2011    35    67    26    46     8     8 0.52239 0.56522 1       0.71642   104 0.73738
##  5 Chris C…   2003     8    13     1     3     7     8 0.61538 0.33333 0.875   0.65385    24 0.72639
##  6 Chris W…   2013   110   153     0     1    39    58 0.71895 0       0.67241 0.71895   259 0.72541
##  7 Maceo B…   2007    49    76     3     7    37    47 0.64474 0.42857 0.78723 0.66447   138 0.71369
##  8 Kyle Ko…   2015   292   600   221   449   106   118 0.48667 0.49220 0.89831 0.67083   911 0.69871
##  9 Jorge G…   2016     6    11     0     2    10    11 0.54545 0       0.90909 0.54545    22 0.69444
## 10 Aleksan…   1997     8    16     5     7     4     5 0.5     0.71429 0.8     0.65625    25 0.68681
## # ℹ 6,711 more rows</code></pre>
<p>For the remainder of this module, we will focus on the non-lockout
seasons (ie <code>!SEASON %in% c(1999, 2012, 2016)</code>) but we still
need to determine a cutoff for FGA and TPA. Let’s start by making
histograms of the two variables to see their individual distributions,
and rather than creating a new temporary <code>tbl</code> we’ll take
advantage of the <code>%&gt;%</code>. First for FGA:</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" tabindex="-1"></a>raw_shooting <span class="sc">%&gt;%</span></span>
<span id="cb23-2"><a href="#cb23-2" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span>SEASON <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">1999</span>, <span class="dv">2012</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb23-3"><a href="#cb23-3" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> FGA)) <span class="sc">+</span></span>
<span id="cb23-4"><a href="#cb23-4" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">50</span>)</span></code></pre></div>
<p><img src="tc_lecture2_files/figure-html/filter%20hist%20fga-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>And now for TPA:</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" tabindex="-1"></a>raw_shooting <span class="sc">%&gt;%</span></span>
<span id="cb24-2"><a href="#cb24-2" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span>SEASON <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">1999</span>, <span class="dv">2012</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb24-3"><a href="#cb24-3" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> TPA)) <span class="sc">+</span></span>
<span id="cb24-4"><a href="#cb24-4" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">25</span>)</span></code></pre></div>
<p><img src="tc_lecture2_files/figure-html/filter%20hist%20tpa-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>It might not make sense however to make a cutoff for FGA and TPA
without considering their relationship.</p>
</div>
<div id="bivariate-plots-for-continuous-data" class="section level2">
<h2>Bivariate plots for continuous data</h2>
<p>We can proceed to view the <strong>joint</strong> distribution of FGA
and TPA, the relationship between the two variables, by displaying a
scatterplot of the data. Obviously, as TPA increases the FGA will
increase (since FGA is the sum of TPA and number of two-point attempts).
We create a scatterplot by mapping multiple variables to <code>x</code>
and <code>y</code>, and use <code>geom_point</code> to display the
desired geometric object of points instead of
<code>geom_histogram</code> from before.</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" tabindex="-1"></a>raw_shooting <span class="sc">%&gt;%</span></span>
<span id="cb25-2"><a href="#cb25-2" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span>SEASON <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">1999</span>, <span class="dv">2012</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb25-3"><a href="#cb25-3" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> TPA, <span class="at">y =</span> FGA)) <span class="sc">+</span></span>
<span id="cb25-4"><a href="#cb25-4" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span></code></pre></div>
<p><img src="tc_lecture2_files/figure-html/geom_point-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Immediately, we notice a few things about the figure. First, we see
the clear relationship between TPA and FGA - where where TPA provides
the lower threshold on FGA (remember why is this expected). We also see
what appears to be a group of points with a smaller number of
three-point attempts displaying a range in values for FGA, while a main
block of points shows an clear increasing relationship. A major drawback
of this scatterplot is its inability to show the relative density of
points. For instance, all we see is a solid black mass for the lower
range of values for both TPA and FGA - making it hard to determine where
an appropriate cutoff should be made.</p>
<p>One way to address this is to use <em>alpha-blending</em> to change
the transparency of each point. When there are many points plotted in
the same region, that region will appear darker. Just like
<code>binwidth</code> or <code>bins</code> for
<code>geom_histogram</code>, <code>geom_point</code> has settings we can
change such as the <code>alpha</code> setting in this case which ranges
from 0 (completely transparent) to 1 (solid and opaque, the
default).</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" tabindex="-1"></a>raw_shooting <span class="sc">%&gt;%</span></span>
<span id="cb26-2"><a href="#cb26-2" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span>SEASON <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">1999</span>, <span class="dv">2012</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb26-3"><a href="#cb26-3" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> TPA, <span class="at">y =</span> FGA)) <span class="sc">+</span></span>
<span id="cb26-4"><a href="#cb26-4" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.1</span>)</span></code></pre></div>
<p><img src="tc_lecture2_files/figure-html/geom_point%20alpha-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Now we have a much better idea of where the majority of points are,
with a clear group of players displaying a smaller number of TPA.
Another type of plot commonly used in this situation is a
<strong>heatmap</strong> which you can thnk of as a two-dimensional
histogram. To form a heatmap, you start by dividing the coordinate plane
into many evenly-sized two-dimensional bins and then count the number of
points within each bin. You then color the bin according to the count.
While you can conceptually make the bins any shape you want, there are
two popular conventions: rectangular binning and hexagonal binning. For
this plot, we will focus on rectangular binning, using the
<code>geom_bin2d()</code> function.</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" tabindex="-1"></a>raw_shooting <span class="sc">%&gt;%</span></span>
<span id="cb27-2"><a href="#cb27-2" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span>SEASON <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">1999</span>, <span class="dv">2012</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb27-3"><a href="#cb27-3" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> TPA, <span class="at">y =</span> FGA)) <span class="sc">+</span></span>
<span id="cb27-4"><a href="#cb27-4" tabindex="-1"></a>  <span class="fu">geom_bin2d</span>()</span></code></pre></div>
<p><img src="tc_lecture2_files/figure-html/geom_bin2d-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Now we have a color scale that has appeared to tell us the number of
points in each bin. Just like histograms, we can increase the number of
bins to get a much more high-resolution view of our data.</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" tabindex="-1"></a>raw_shooting <span class="sc">%&gt;%</span></span>
<span id="cb28-2"><a href="#cb28-2" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span>SEASON <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">1999</span>, <span class="dv">2012</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb28-3"><a href="#cb28-3" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> TPA, <span class="at">y =</span> FGA)) <span class="sc">+</span></span>
<span id="cb28-4"><a href="#cb28-4" tabindex="-1"></a>  <span class="fu">geom_bin2d</span>(<span class="at">bins =</span> <span class="dv">100</span>)</span></code></pre></div>
<p><img src="tc_lecture2_files/figure-html/geom_bin2d%20bins-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>In this example, using <code>geom_point</code> with lower values for
<code>alpha</code> provides a clear interpretation for where to make the
cutoff. Given the histograms we previously made for each variable as
well, let’s use a cutoff of <code>TPA &gt; 50</code> and
<code>FGA &gt; 150</code>. We can create the scatterplot as before but,
to demonstrate a convenient feature of <code>ggplot2</code>, we’ll now
assign the plot to a variable named <code>fga_tpa_plot</code>,</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" tabindex="-1"></a>fga_tpa_plot <span class="ot">&lt;-</span> raw_shooting <span class="sc">%&gt;%</span></span>
<span id="cb29-2"><a href="#cb29-2" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span>SEASON <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">1999</span>, <span class="dv">2012</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb29-3"><a href="#cb29-3" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> TPA, <span class="at">y =</span> FGA)) <span class="sc">+</span></span>
<span id="cb29-4"><a href="#cb29-4" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.1</span>)</span></code></pre></div>
<p>Notice how this code runs without displaying the plot. To display it
we simplyrun <code>fga_tpa_plot</code> in the console and the plot
appear,</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" tabindex="-1"></a>fga_tpa_plot</span></code></pre></div>
<p><img src="tc_lecture2_files/figure-html/run%20fga_tpa_plot-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Now we’re going to annotate this plot with the cutoffs we’ve
determined. To do so, we’re going to add a vertical line to provide the
cutoff for the minimum value of TPA, and a horizontal line for the
minimum value of FGA. Both of these can be accomplished using the
<code>geom</code>s <code>geom_vline</code> and <code>geom_hline</code>
where we specify for each the values for the intercepts to draw the
lines at. Since we’ve stored the plot in <code>fga_tpa_plot</code>, we
can add these layers with the <code>+</code> operator to
<code>fga_tpa_plot</code> directly:</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" tabindex="-1"></a>fga_tpa_plot <span class="sc">+</span></span>
<span id="cb31-2"><a href="#cb31-2" tabindex="-1"></a>  <span class="co"># Add TPA cutoff</span></span>
<span id="cb31-3"><a href="#cb31-3" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">50</span>) <span class="sc">+</span></span>
<span id="cb31-4"><a href="#cb31-4" tabindex="-1"></a>  <span class="co"># Add FGA cutoff</span></span>
<span id="cb31-5"><a href="#cb31-5" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">150</span>)</span></code></pre></div>
<p><img src="tc_lecture2_files/figure-html/add%20lines-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>This provides us with a good indication of what we’re cutting off,
but we should distinguish these lines separately from the points more.
Since these are both <code>geom</code>s with their own set of
attributes, we’ll change the color and make the line type to be
dashed,</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" tabindex="-1"></a>fga_tpa_plot <span class="sc">+</span></span>
<span id="cb32-2"><a href="#cb32-2" tabindex="-1"></a>  <span class="co"># Add TPA cutoff</span></span>
<span id="cb32-3"><a href="#cb32-3" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">50</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>) <span class="sc">+</span></span>
<span id="cb32-4"><a href="#cb32-4" tabindex="-1"></a>  <span class="co"># Add FGA cutoff</span></span>
<span id="cb32-5"><a href="#cb32-5" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">150</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>)</span></code></pre></div>
<p><img src="tc_lecture2_files/figure-html/add%20lines%20dashed-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Although <code>ggplot2</code> automatically provides axis labels
based on the variables we’ve mapped to the aesthetics in
<code>aes</code>, we really need text describing what is shown in the
plot. The easiest way to do this, is by adding a label layer with the
<code>labs()</code> function. Using <code>labs</code>, you can provide
it the same arguments as those inside <code>aes</code> as well as other
parts of the plot to label such as the title, subtitle, and caption. We
add appropriate labels to the plot above, with better descriptions for
the axes, as well as an informative subtitle regarding the red-dashed
lines:</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" tabindex="-1"></a>fga_tpa_plot <span class="sc">+</span></span>
<span id="cb33-2"><a href="#cb33-2" tabindex="-1"></a>  <span class="co"># Add TPA cutoff</span></span>
<span id="cb33-3"><a href="#cb33-3" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">50</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>) <span class="sc">+</span></span>
<span id="cb33-4"><a href="#cb33-4" tabindex="-1"></a>  <span class="co"># Add FGA cutoff</span></span>
<span id="cb33-5"><a href="#cb33-5" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">150</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>) <span class="sc">+</span></span>
<span id="cb33-6"><a href="#cb33-6" tabindex="-1"></a>  <span class="co"># Add appropriate labels:</span></span>
<span id="cb33-7"><a href="#cb33-7" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Number of three point attempts (TPA)&quot;</span>,</span>
<span id="cb33-8"><a href="#cb33-8" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Number of field goal attempts (FGA)&quot;</span>,</span>
<span id="cb33-9"><a href="#cb33-9" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">&quot;Scatterplot of FGA and TPA (excluding lockout seasons 1999 and 2012)&quot;</span>,</span>
<span id="cb33-10"><a href="#cb33-10" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">&quot;Red-dashed lines indicate cutoffs for TPA &gt; 50 and FGA &gt; 150&quot;</span>,</span>
<span id="cb33-11"><a href="#cb33-11" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">&quot;Created by INSERT YOUR NAME HERE&quot;</span>)</span></code></pre></div>
<p><img src="tc_lecture2_files/figure-html/add%20labs-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>As a reminder, the code chunk above is equivalent to running the
entire pipeline of code without creating any temporary objects, although
not recommended…</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" tabindex="-1"></a><span class="fu">read_csv</span>(<span class="at">file =</span> <span class="st">&quot;data/nba_shooting.csv&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb34-2"><a href="#cb34-2" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span>SEASON <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">1999</span>, <span class="dv">2012</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb34-3"><a href="#cb34-3" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> TPA, <span class="at">y =</span> FGA)) <span class="sc">+</span></span>
<span id="cb34-4"><a href="#cb34-4" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.1</span>) <span class="sc">+</span></span>
<span id="cb34-5"><a href="#cb34-5" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">50</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>) <span class="sc">+</span></span>
<span id="cb34-6"><a href="#cb34-6" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">150</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>) <span class="sc">+</span></span>
<span id="cb34-7"><a href="#cb34-7" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Number of three point attempts (TPA)&quot;</span>,</span>
<span id="cb34-8"><a href="#cb34-8" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Number of field goal attempts (FGA)&quot;</span>,</span>
<span id="cb34-9"><a href="#cb34-9" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">&quot;Scatterplot of FGA and TPA (excluding lockout seasons 1999 and 2012)&quot;</span>,</span>
<span id="cb34-10"><a href="#cb34-10" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">&quot;Red-dashed lines indicate cutoffs for TPA &gt; 50 and FGA &gt; 150&quot;</span>,</span>
<span id="cb34-11"><a href="#cb34-11" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">&quot;Created by INSERT YOUR NAME HERE&quot;</span>)</span></code></pre></div>
<p><img src="tc_lecture2_files/figure-html/run%20entire%20pipeline-1.png" width="672" style="display: block; margin: auto;" /></p>
</div>
<div id="saving-our-work" class="section level2">
<h2>Saving our work</h2>
<p>For the next <a href="tc_lecture3.html">lecture</a> we will focus on
the dataset of players who attempted at least 150 field goals and 50
three pointers in the non-lockout seasons. We’ll make this
<em>clean</em> dataset using the <code>filter()</code> function
separating each condition with commas, and refer to the resulting
dataset as <code>nba_shooting</code>. Finally, we’ll add a
<code>mutate()</code> line to create the
<code>three_point_fg_rate = TPA / FGA</code> variable from <a
href="tc_lecture1.html">yesterday</a>.</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" tabindex="-1"></a>nba_shooting <span class="ot">&lt;-</span> raw_shooting <span class="sc">%&gt;%</span></span>
<span id="cb35-2"><a href="#cb35-2" tabindex="-1"></a>  <span class="co"># Filter on the conditions</span></span>
<span id="cb35-3"><a href="#cb35-3" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span>SEASON <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">1999</span>, <span class="dv">2012</span>),</span>
<span id="cb35-4"><a href="#cb35-4" tabindex="-1"></a>         TPA <span class="sc">&gt;</span> <span class="dv">50</span>,</span>
<span id="cb35-5"><a href="#cb35-5" tabindex="-1"></a>         FGA <span class="sc">&gt;</span> <span class="dv">150</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb35-6"><a href="#cb35-6" tabindex="-1"></a>  <span class="co"># Create the three point attempt rate variable</span></span>
<span id="cb35-7"><a href="#cb35-7" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">three_point_fg_rate =</span> TPA <span class="sc">/</span> FGA)</span></code></pre></div>
<p>While we can always re-run the commands used to produce this
<code>tbl</code> from our script, when data analyses become more
complicated, it is helpful to save these objects. <code>R</code> has its
own special file format for efficiently saving data on your
computer.</p>
<p>We will use the <code>save()</code> command.</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" tabindex="-1"></a><span class="fu">save</span>(nba_shooting, <span class="at">file =</span> <span class="st">&quot;data/clean_nba_shooting.RData&quot;</span>)</span></code></pre></div>
<p>Then when we want to <em>load</em> the data back into R, we can use
the <code>load()</code> function.</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" tabindex="-1"></a><span class="fu">load</span>(<span class="st">&quot;data/clean_nba_shooting.RData&quot;</span>)</span></code></pre></div>
<p>Next, proceed to practice this lecture’s lessons in <a
href="tc_ps2.html">Problem Set 2</a>.</p>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
